---
title: "Diamonds Price Predictions"
output: html_document
---

Import libraries
```{r}
library(ggplot2)
```


```{r}
ggplot(data=diamonds, aes(x=carat, y=price)) + geom_point() +
  coord_cartesian(xlim=c(0, quantile(diamonds$carat, 0.99)), ylim=c(0, quantile(diamonds$price, 0.99)))
```

```{r}

library(gridExtra)

plot1 <- ggplot(data=diamonds, aes(x=price)) + geom_histogram()
  ggtitle('Price')

plot2 <- ggplot(data=diamonds, aes(x=price)) + geom_histogram() + scale_x_log10()
  ggtitle('Price (log10)')

grid.arrange(plot1, plot2, ncol=2)
```

```{r}
cuberoot_trans = function() trans_new('cuberoot', 
                                      transform = function(x) x^(1/3),
inverse = function(x) x^3)
```

```{r}
ggplot(aes(carat, price), data = diamonds) + 
  geom_point() + 
  scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2, 3),
                     breaks = c(0.2, 0.5, 1, 2, 3)) + 
  scale_y_continuous(trans = log10_trans(), limits = c(350, 15000),
                     breaks = c(350, 1000, 5000, 10000, 15000)) +
  ggtitle('Price (log10) by Cube-Root of Carat')
```


