---
title: "One Variable - Problem Set"
output: 
  html_document: 
    keep_md: yes
---

Import necessary libraries and data sets
```{r message=FALSE, warning=FALSE}
library(ggplot2)
data(diamonds)
```

Setting seed for reproducibility
```{r}
set.seed(1234)
```

Histogram of diamond prices
```{r message=FALSE, warning=FALSE}
dp_hist <- qplot(x = price, data = diamonds, binwidth = 30
      , color = I('black'), fill = I('blue')) +
  xlab("Diamond prices") +
  ylab("Number of diamonds") +
  scale_x_continuous(limits = c(0, 1500), breaks = seq(0, 1500, 100))
dp_hist
```

Zooming into the histogram's peak
```{r message=FALSE, warning=FALSE}
dp_hist +
  scale_x_continuous(limits = c(0, 1500), breaks = seq(0, 1500, 100))
```

How many diamonds cost less than $500?
```{r}
nrow(subset(diamonds, price < 500))
```
How many diamonds cost less than $250?
```{r}
nrow(subset(diamonds, price < 250))
```
How many diamonds cost $15000 or more?
```{r}
nrow(subset(diamonds, price <= 15000))
```

```{r message=FALSE, warning=FALSE}
qplot(x = price, data = diamonds, binwidth = 30
      , color = I('black'), fill = I('blue')) +
  xlab("Diamond prices") +
  ylab("Number of diamonds") +
  facet_wrap(~cut, scales="free_y") +
  ggtitle("Histograms of diamond prices by cut")
```

Numerical summary of diamond prices by cut
```{r}
by(diamonds$price, diamonds$cut, summary, digits = max(getOption('digits')))
```

```{r message=FALSE, warning=FALSE}
qplot(x = (price/carat), data = diamonds, binwidth = .05
      , color = I('black'), fill = I('blue')) +
  xlab("Diamond price per carat") +
  ylab("Number of diamonds") +
  scale_x_log10() +
  facet_wrap(~cut, scales="free_y") +
  ggtitle("Histogram of price per carat faceted by cut")
```

```{r message=FALSE, warning=FALSE}
qplot(x = carat, data = diamonds, geom = 'freqpoly', binwidth=.05) +
  scale_x_continuous(breaks=seq(0, 2, .1)) +
  scale_y_continuous(breaks=seq(0, 2500, 500)) +
  xlab("Diamond carat") +
  ylab("Number of diamonds") +
  ggtitle("Carat frequency polygon")
```

